### PR TITLE
Hyperopt

### PR DESCRIPTION
**Pull request by lucas-FP**
Hyperopt search method integration

### CODE REVIEW

**Comment by apiad** [comment]
So far it's looking great! The test is failing because we need to `poetry lock`, that's a minor thing. I'm very excited to have hyperopt included and to compare it with the PGE search. 

If it's not too much to ask, do you think you could add one or two examples (in `tests/examples`) when everything is in place, to have this feature added to the documentation?

Thanks @lucas-FP, great work!!

**Comment by apiad** [comment]
Hey @lucas-FP, now that the summer is over and we're returning to work, we'll be focusing again on polishing `autogoal` for a `v1.0` release. It's gonna bring some changes to the way contribs work, mainly by removing the dependencies from the `pyproject.toml` for everything that's not core, and having a separate `requirements.txt` in each contrib's folder. This should make it easier to develop contribs that don't get too well along with each other as long as they don't mess with the core :)

Anyway, just wanted to give you the heads up, let us know if you need any help or want to discuss anything at some point. Cheers :)

**Comment by lucas-FP** [comment]
> Hey @lucas-FP, now that the summer is over and we're returning to work, we'll be focusing again on polishing `autogoal` for a `v1.0` release. It's gonna bring some changes to the way contribs work, mainly by removing the dependencies from the `pyproject.toml` for everything that's not core, and having a separate `requirements.txt` in each contrib's folder. This should make it easier to develop contribs that don't get too well along with each other as long as they don't mess with the core :)
> 
> Anyway, just wanted to give you the heads up, let us know if you need any help or want to discuss anything at some point. Cheers :)

Hey @apiad, I completely forgot to answer your first comment, sorry for that.

During the last months I was busy finishing my final project's paper.

During this time I made a lot of corrections to the hyperopt intefration, but those are in another branch and all bundled up with unecessary changes. The next step will be to organize it and merge it with this branch. If I need any help with the new way dependencies are handled I'll let you know.

**Comment by lucas-FP** [comment]
Hey @apiad, sorry for the delay, I had to focus myself on some other issues for the past months. Last week I took some time to organize the commits and merge them to this hyperopt "main" branch. In the end. Hyperopt's integration is not working as well as I wanted it to. There are still some rough edges, but I don't think they can be solved easily. The main issue is that it cannot handle Keras algorithms yet, because they are represented in a different kind of space when compared to the others. Nonetheless, there are some improvements I made that could be used without the hyperopt integration:
1. I created a new type called `UniformSeq`, that is a sequence whose items have uniform length. Also made a padder algorithm to transform `Seq`s into `UniformSeq`s. This enables the user to just enter text documents (in the example of an NLP problem) without having to worry about tokenizing and padding the text beforehand. This type should be considered a subtype of `Seq`, but the `conforms` method is still buggy and I will try to figure it out. The failing test is because of this feature.
2. Created a preemptive stop feature. My tests were taking too long and I noticed that I could just skip the rest of the training if I noticed it would timeout after the first training epoch. This saved me a lot of time, and I think it would be useful. To "solve" the issue of not being able to use Keras algorithms with hyperopt, I created some Keras presets and use them. I also included a preemptive timeout check after each training epoch of the network. Maybe this could be implemented for all keras algorithms.
3. There were a number of smaller bug fixes as well.

Do you prefer that I take some more time to split these features into separate PRs?

**Comment by apiad** [comment]
Hey Lucas! Nice to hear from you :) I figured you got complicated with other stuff, so don't worry, we all did. I haven't looked at autogoal seriously since a couple of months ago as I had to focus on finishing my PhD which I happily defended in December!

So, the `UniformSeq` and the preemptive stopping seem like pretty useful stuff, thanks for that. We're pushing to have a v1.0 release by early March because we have a conference deadline coming up so we want to clean up and polish what's already working. For that reason I don't think we'll merge something as complex and full of functionality as this PR at least until after April, so there's plenty of time if you want to polish some stuff, and I can also pull your branch if you want to have any discussion at any point.

Regarding making this into multiple PRs, I think that would be nice but only if it's not a massive amount of work. If you think it's something you can do easily, go ahead, but if it's gonna take you dunno a couple of weeks or something like that, then I don't think it's worth it, especially because we'll end up merging pretty much all those PRs simultaneously.

Anyway, good to have you back, let's take from here!

**Comment by lucas-FP** [comment]
I think it is not going to be too hard to break this into separate PRs. Just created [another PR](https://github.com/autogoal/autogoal/pull/153) with some fixes from this branch that I believe should be included before v1.0 release.
I will work a little bit more to polish the other features before submitting more PRs.

**Comment by apiad** [comment]
Got it, I'll check those PRs as they come. Thanks again!

**Pull request closed without merging**
