### PR TITLE
fix:Refactor dependencies #10

### PR DESCRIPTION
**Pull request by AnshuTrivedi**
* Removed contrib dependencies from [tool.poetry.dev-dependencies]
* Add [tool.poetry.extras] and enlisted contrib dependencies

### CODE REVIEW

**Review by apiad — CHANGES_REQUESTED** [review]
I guess I commented in the wrong pull request, so I'll repeat it here.

First, thanks :pray: for this!

I think these can also be extras:
- `seqlearn`
- `sklearn_crfsuite`
- `streamlit`
- `transformers`

And I don't know why `matplotlib` is there, I'll have to check where is used.

Finally, we should check which tests fail and refactor wherever something is being referenced that shouldn't. I'll help you with this task.

**Comment by AnshuTrivedi** [comment]
If you can also add hacktoberfest20 as topics in your repo , it will help me to be counted in hacktoberfest as well.

**Comment by apiad** [comment]
> hacktoberfest20

Or hacktoberfest2020 ??

**Comment by AnshuTrivedi** [comment]
> I guess I commented in the wrong pull request, so I'll repeat it here.
> 
> First, thanks 🙏 for this!
> 
> I think these can also be extras:
> 
> * `seqlearn`
> * `sklearn_crfsuite`
> * `streamlit`
> * `transformers`
> 
> And I don't know why `matplotlib` is there, I'll have to check where is used.
> 
> Finally, we should check which tests fail and refactor wherever something is being referenced that shouldn't. I'll help you with this task.

I will add these dependencies as well .
* `seqlearn`
> * `sklearn_crfsuite`
> * `streamlit`
> * `transformers`
Thank you for helping me in CI tests failing.

**Comment by AnshuTrivedi** [comment]
> > hacktoberfest20
> 
> Or hacktoberfest2020 ??

[✔️ :]hacktoberfest2020

**Comment by apiad** [comment]
I think what's failing in the CI so far is the format for the `[...extras]` section.

If you check here: https://python-poetry.org/docs/pyproject/#extras

I think we have to do it like this:

```[tool.poetry.dependencies]
# Mandatory packages
# ...

# Optional packages, each with optional = true
scikit-learn = { version = "^0.22", optional = true }
seqlearn = { version = "^0.2", optional = true }
# ... all the other extras here

[tool.poetry.extras]
# And here just bundle them under the corresponding contrib package if there is more than one
sklearn = ["scikit-learn", "seqlearn"]

# And maybe stuff like
nlp = ["nltk", "gensim", "spacy"]
```

We can figure out the bundles later. For now, I think just refactoring to the `{ version = ..., optional = true }` would be great!

**Comment by AnshuTrivedi** [comment]
> { version = ..., optional = true }

For now I'm  doing this way.
{ version = ..., optional = true }
Is that okay?

**Comment by apiad** [comment]
Yes, I think it's ok, but instead of in the [extras] section just put them in the [.dependencies] section. Once the tests pass, we will create the extras bundles. :+1:

**Comment by apiad** [comment]
As for the extras, for the time being I think I would just have:

`sklearn = ["scikit-learn", "seqlearn", "sklearn_crfsuite"]`

And 

`all = [ ... everything optional ...]`

And let's see if that works when installing the Docker. I'll check that part once the tests pass.

**Comment by apiad** [comment]
So, there are some errors in the installation. I would check them locally to see what is happening, is probably just a minor detail :sweat_smile:

**Comment by AnshuTrivedi** [comment]
@apiad i tried to change as per poetry format for extras now another problem. 
Hope it will resolve by tomorrow.

**Comment by apiad** [comment]
> @apiad i tried to change as per poetry format for extras now another problem.
> Hope it will resolve by tomorrow.

Don't worry, we'll figure it out. It just takes a few steps.

**Comment by AnshuTrivedi** [comment]
@apiad 
Adding import scipy [here](https://github.com/autogoal/autogoal/blob/126ddde3367452a799ee894440a8aad284aa941b/autogoal/kb/_data.py#L4)  i.e in _data.py file may solve issue .
What you think?

**Review by AnshuTrivedi — COMMENTED** [review]
@apiad  I think removing pytoch has no impact in test failing.
There is issue with scipy. I didn't see it in dependencies. 
May be adding `import scipy` in _data.py file may solve issue in this commit.

**Comment by apiad** [comment]
> @apiad I think removing pytoch has no impact in test failing.
> There is issue with scipy. I didn't see it in dependencies.
> May be adding `import scipy` in _data.py file may solve issue in this commit.

You could try. But I think the issue now is that scipy is not installed, because previously it was a secondary dependency of someone (possibly sklearn) and since it has always been there, it is being used through autogoal, but now that we made sklearn optional, we need to make scipy explicit. Possibly numpy as well. I'm gonna take a look locally to see if I can define all the mandatory dependencies correctly.

**Comment by apiad** [comment]
I've trying to work on this, it is harder than we first thought. The problem is now we need a separate testing environment only for the "basic" version of autogoal, because the current testing environment is on a fully configured Docker image. 

What I think I'm gonna do, is to setup a test-install command that builds a new Docker image from scratch and just installs and runs basic tests. Let's see :crossed_fingers:

**Comment by apiad** [comment]
Continuing in #17

**Pull request closed without merging**
